name: sdk-acdc
services:
  bbe_sdk_acdc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbe_sdk_acdc
    command: python main_acdc.py
    environment:
      - MODEL_TYPE=acdc
    volumes:
      - ./example_model:/app/example_model:ro
      - ./user_id_acdc.txt:/app/user_id_acdc.txt
    networks:
      - tpp-network

networks:
  tpp-network:
    external: true
